package model.ERP.EO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 10 12:55:58 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TblAssetReturnDImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        AssetReturnMId,
        SrNo,
        AssetL4Id,
        Description,
        Qty,
        Rate,
        Amount,
        CreatedDate,
        CreatedBy,
        UpdatedDate,
        UpdatedBy,
        PurchQty,
        AssetPurchMId,
        AssetPurchMVtp,
        TblAssetL4,
        TblAssetReturnM;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int ASSETRETURNMID = AttributesEnum.AssetReturnMId.index();
    public static final int SRNO = AttributesEnum.SrNo.index();
    public static final int ASSETL4ID = AttributesEnum.AssetL4Id.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int PURCHQTY = AttributesEnum.PurchQty.index();
    public static final int ASSETPURCHMID = AttributesEnum.AssetPurchMId.index();
    public static final int ASSETPURCHMVTP = AttributesEnum.AssetPurchMVtp.index();
    public static final int TBLASSETL4 = AttributesEnum.TblAssetL4.index();
    public static final int TBLASSETRETURNM = AttributesEnum.TblAssetReturnM.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TblAssetReturnDImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for AssetReturnMId, using the alias name AssetReturnMId.
     * @return the value of AssetReturnMId
     */
    public BigDecimal getAssetReturnMId() {
        return (BigDecimal) getAttributeInternal(ASSETRETURNMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetReturnMId.
     * @param value value to set the AssetReturnMId
     */
    public void setAssetReturnMId(BigDecimal value) {
        setAttributeInternal(ASSETRETURNMID, value);
    }

    /**
     * Gets the attribute value for SrNo, using the alias name SrNo.
     * @return the value of SrNo
     */
    public Integer getSrNo() {
        return (Integer) getAttributeInternal(SRNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrNo.
     * @param value value to set the SrNo
     */
    public void setSrNo(Integer value) {
        setAttributeInternal(SRNO, value);
    }

    /**
     * Gets the attribute value for AssetL4Id, using the alias name AssetL4Id.
     * @return the value of AssetL4Id
     */
    public BigDecimal getAssetL4Id() {
        return (BigDecimal) getAttributeInternal(ASSETL4ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetL4Id.
     * @param value value to set the AssetL4Id
     */
    public void setAssetL4Id(BigDecimal value) {
        setAttributeInternal(ASSETL4ID, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Qty, using the alias name Qty.
     * @return the value of Qty
     */
    public BigDecimal getQty() {
        return (BigDecimal) getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty.
     * @param value value to set the Qty
     */
    public void setQty(BigDecimal value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for Rate, using the alias name Rate.
     * @return the value of Rate
     */
    public BigDecimal getRate() {
        return (BigDecimal) getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rate.
     * @param value value to set the Rate
     */
    public void setRate(BigDecimal value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedDate, using the alias name UpdatedDate.
     * @return the value of UpdatedDate
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for PurchQty, using the alias name PurchQty.
     * @return the value of PurchQty
     */
    public BigDecimal getPurchQty() {
        return (BigDecimal) getAttributeInternal(PURCHQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PurchQty.
     * @param value value to set the PurchQty
     */
    public void setPurchQty(BigDecimal value) {
        setAttributeInternal(PURCHQTY, value);
    }

    /**
     * Gets the attribute value for AssetPurchMId, using the alias name AssetPurchMId.
     * @return the value of AssetPurchMId
     */
    public BigDecimal getAssetPurchMId() {
        return (BigDecimal) getAttributeInternal(ASSETPURCHMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetPurchMId.
     * @param value value to set the AssetPurchMId
     */
    public void setAssetPurchMId(BigDecimal value) {
        setAttributeInternal(ASSETPURCHMID, value);
    }

    /**
     * Gets the attribute value for AssetPurchMVtp, using the alias name AssetPurchMVtp.
     * @return the value of AssetPurchMVtp
     */
    public String getAssetPurchMVtp() {
        return (String) getAttributeInternal(ASSETPURCHMVTP);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetPurchMVtp.
     * @param value value to set the AssetPurchMVtp
     */
    public void setAssetPurchMVtp(String value) {
        setAttributeInternal(ASSETPURCHMVTP, value);
    }

    /**
     * @return the associated entity TblAssetL4Impl.
     */
    public TblAssetL4Impl getTblAssetL4() {
        return (TblAssetL4Impl) getAttributeInternal(TBLASSETL4);
    }

    /**
     * Sets <code>value</code> as the associated entity TblAssetL4Impl.
     */
    public void setTblAssetL4(TblAssetL4Impl value) {
        setAttributeInternal(TBLASSETL4, value);
    }

    /**
     * @return the associated entity TblAssetReturnMImpl.
     */
    public TblAssetReturnMImpl getTblAssetReturnM() {
        return (TblAssetReturnMImpl) getAttributeInternal(TBLASSETRETURNM);
    }

    /**
     * Sets <code>value</code> as the associated entity TblAssetReturnMImpl.
     */
    public void setTblAssetReturnM(TblAssetReturnMImpl value) {
        setAttributeInternal(TBLASSETRETURNM, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.ERP.EO.TblAssetReturnD");
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Number loginId = null;
                        try {
                            loginId = new Number((String) ADFContext.getCurrent().getSessionScope().get("sessUMID"));
                        } catch(Exception ex) {
                            ex.printStackTrace();
                        }
                        
                        if (operation == DML_INSERT) {
                            setCreatedBy(loginId);
                            setUpdatedBy(loginId);
                            } else if(operation == DML_UPDATE) {
                            setUpdatedBy(loginId);
                        }
        super.doDML(operation, e);
    }
}

